module.exports = {
    mode: 'jit', // 'jit' 'aot'
    purge: [  // NODE_ENV=production && ng build - whet using 'aot + purge'
        './src/**/*{html, ts}'
    ],
    darkMode: false, // or 'media' or 'class'
    theme: {
        extend: {
            height: {
                "7v": "7vh",
                "8v": "8vh",
                "8.5v": "8.5vh",
                "9v": "9vh",
                "10v": "10vh",
                "20v": "20vh",
                "30v": "30vh",
                "40v": "40vh",
                "50v": "50vh",
                "60v": "60vh",
                "70v": "70vh",
                "80v": "80vh",
                "90v": "90vh",
                "100v": "100vh",
            },
            width: {
                "7v": "7vw",
                "8v": "8vw",
                "8.5v": "8.5vw",
                "9v": "9vw",
                "10v": "10vw",
                "20v": "20vw",
                "21v": "21vw",
                "22v": "22vw",
                "23v": "23vw",
                "24v": "24vw",
                "25v": "25vw",
                "30v": "30vw",
                "40v": "40vw",
                "50v": "50vw",
                "60v": "60vw",
                "70v": "70vw",
                "80v": "80vw",
                "90v": "90vw",
                "100v": "100vw",
            },
            maxWidth: {
                "4": "1rem",
                "5": "1.25rem",
                "6": "1.5rem",
                "7": "1.75rem",
                "8": "2rem",
                "9": "2.25rem",
                "10": "2.5rem",
                "11": "2.75rem",
                "12": "3rem",
                "14": "3.5rem",
                "16": "4rem",
                "20": "5rem",
                "24": "6rem",
                "28": "7rem",
                "32": "8rem",
                "36": "9rem",
                "40": "10rem",
                "44": "11rem",
                "48": "12rem",
                "52": "13rem",
                "56": "14rem",
                "60": "15rem",
                "64": "16rem",
                "72": "18rem",
                "80": "20rem",
                "96": "24rem",
            }
        },
    },
    variants: {
        extend: {},
    },
    plugins: [],
}
